name: Devcontainer

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  devcontainer:
    name: Devcontainer build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/ssoudan/unit-root-devcontainer
          cacheFrom: ghcr.io/ssoudan/unit-root-devcontainer:latest
          push: always